import network
import urequests
import ujson
import time

# --- 1. SIMULATED SENSORS (Global Configuration) ---
PLANT_NAME = "Succulents"
TEMP_VALUE = -3   # Simulated Temperature in Celsius (Very cold!)
SOIL_VALUE = 0    # Simulated Soil Moisture Percentage (Extremely dry!)
LIGHT_VALUE = 0   # Simulated Light Intensity Percentage (Pitch black!)

# --- 2. NETWORK & SERVER CONFIGURATION ---
WIFI_SSID = "Your_WiFi_Name"
WIFI_PASSWORD = "Your_WiFi_Password"
# Replace with your local PC IP address found in Step 3
OLLAMA_API_URL = "http://10.0.0.27:11434/api/generate" 
#LOCAL_MODEL_NAME = "gemma:2b"  # Ensure this matches your downloaded model name
LOCAL_MODEL_NAME = "gemma4:e4b"  # Ensure this matches your downloaded model name

# --- 3. TIMING CONFIGURATION ---
MEASUREMENT_INTERVAL = 10 

def connect_to_wifi():
    """Connects the ESP32 board to the local Wi-Fi network."""
    print("Starting Wi-Fi connection process...")
    wlan = network.WLAN(network.STA_IF)
    wlan.active(True)
    wlan.connect(WIFI_SSID, WIFI_PASSWORD)
    
    # Wait until connection is successful
    while not wlan.isconnected():
        print("Connecting to network... Please wait.")
        time.sleep(1)
        
    print("Successfully connected to Wi-Fi!")
    print("ESP32 IP Address configuration:", wlan.ifconfig()[0])

def build_prompt(plant, temp, soil, light):
    """Constructs the prompt with current sensor values using Python string formatting."""
    prompt_template = (
        "You are an AI Agro-tech expert evaluating plant sensor data.\n"
        "Analyze the input and respond ONLY with a raw JSON object. "
        "Do not include markdown blocks, no explanations, and no extra text.\n\n"
        "Input format:\n"
        "Plant: [Name], Temp: [Celsius], Soil: [Percentage], Light: [Percentage]\n\n"
        "Output JSON schema layout:\n"
        "{{\n"
        '  "lcd": "Strictly max 16 characters text for LCD screen",\n'
        '  "pump": "ON" or "OFF",\n'
        '  "lamp": "ON" or "OFF",\n'
        '  "fan": "ON" or "OFF",\n'
        '  "reason": "One short sentence explanation"\n'
        "}}\n\n"
        "Rules for decision making:\n"
        '1. If Soil is below 30%, set pump to "ON". Otherwise "OFF".\n'
        '2. If Light is below 40%, set lamp to "ON". Otherwise "OFF".\n'
        '3. If Temp is above 30C, set fan to "ON". Otherwise "OFF".\n\n'
        "Example Input:\n"
        "Plant: Tomato, Temp: 32, Soil: 15, Light: 85\n\n"
        "Example Output:\n"
        '{{"lcd":"Watering Tomato","pump":"ON","lamp":"OFF","fan":"ON","reason":"Soil is too dry and temperature is high."}}\n\n'
        "Current Input to process:\n"
        "Plant: {}, Temp: {}, Soil: {}, Light: {}\n"
    )
    return prompt_template.format(plant, temp, soil, light)

def query_local_llm(prompt_text):
    """Sends the formatted prompt to the local LLM and returns ONLY the inner response text."""
    payload = {
        "model": LOCAL_MODEL_NAME,
        "prompt": prompt_text,
        "stream": False
    }
    headers = {"Content-Type": "application/json; charset=utf-8"}
    
    try:
        print("Sending sensor data payload to Local LLM...")
        response = urequests.post(OLLAMA_API_URL, json=payload, headers=headers)
        
        # Parse the outer Ollama response JSON
        ollama_envelope = response.json()
        response.close()
        
        # Extract only the actual text response generated by the LLM
        llm_text_output = ollama_envelope.get("response", "")
        return llm_text_output
        
    except Exception as error:
        print("Network error during API call:", error)
        return None

def process_response_and_control(raw_response):
    """Cleans up the raw LLM output, parses the JSON, and simulates hardware outputs."""
    if raw_response is None:
        print("Error: No data to process.")
        return

    try:
        # Clean potential markdown backticks that the LLM might have included
        cleaned_text = raw_response.replace("```json", "").replace("```", "").strip()
        
        # Parse the JSON string into a Python dictionary
        data_dict = ujson.loads(cleaned_text)
        
        # Extract fields from the parsed dictionary
        lcd_msg = data_dict.get("lcd", "N/A")
        pump_state = data_dict.get("pump", "OFF")
        lamp_state = data_dict.get("lamp", "OFF")
        fan_state = data_dict.get("fan", "OFF")
        reason_msg = data_dict.get("reason", "No reason provided.")
        
        # --- Simulating Hardware Outputs with print statements ---
        print("\n================== HARDWARE STATUS ==================")
        print(" [LCD SCREEN]:", lcd_msg)
        print(" [WATER PUMP]:", pump_state)
        print(" [HEATING LAMP]:", lamp_state)
        print(" [COOLING FAN]:", fan_state)
        print(" [SYSTEM REASONING]:", reason_msg)
        print("=====================================================")
        
    except Exception as error:
        print("Error while parsing JSON or controlling hardware:", error)
        print("Raw output was:", raw_response)

# --- MAIN EXECUTION LOOP ---

# 1. Initialize Wi-Fi connection
connect_to_wifi()

# 2. Start the periodic monitoring loop
while True:
    print("\n--- Starting New Sensor Measurement Cycle ---")
    print("Simulated Sensor Values -> Plant: {}, Temp: {}C, Soil: {}%, Light: {}%".format(
        PLANT_NAME, TEMP_VALUE, SOIL_VALUE, LIGHT_VALUE
    ))
    
    # 3. Construct the detailed prompt
    complete_prompt = build_prompt(PLANT_NAME, TEMP_VALUE, SOIL_VALUE, LIGHT_VALUE)
    
    # 4. Query the Ollama API
    api_response = query_local_llm(complete_prompt)
    
    # 5. Extract the LLM's decision and apply it to the simulated hardware
    process_response_and_control(api_response)
    
    # 6. Wait before the next measurement cycle
    print("Cycle complete. Waiting {} seconds before next check...".format(MEASUREMENT_INTERVAL))
    time.sleep(MEASUREMENT_INTERVAL)
